/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import java.util.*;
import icfes_proJect.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author jalco
 */
public class frFiltro extends javax.swing.JFrame {
    JCheckBox[] checks;
    FormMain fmain;
    LinkedList<String> titulos = new LinkedList<String>();
    Titles titles; 
    String periodo;
    /**
     * Creates new form frFiltro
     */
    public frFiltro() {
        initComponents();
        
    }
     public frFiltro(String periodo,FormMain fmain) {
        this.periodo = periodo;
        titles  = new Titles(periodo);
        this.fmain = fmain;
        initComponents();
        this.cargar();
       
       
        
        
    }
     
    public void cargar (){

        String[] tit = titles.getTitles();
        this.pnFiltro.setLayout(new GridLayout(tit.length/4,2,8,8));
        checks = new JCheckBox[tit.length]; 
        System.out.print(tit[0]);
        System.out.print(tit.length);
        for(int i=0;i<tit.length;i++){
            JCheckBox aux = new JCheckBox(tit[i]);
            checks[i] = aux;
            this.pnFiltro.add(checks[i]);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFiltro = new javax.swing.JPanel();
        chtodos = new javax.swing.JCheckBox();
        btEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnFiltro.setBackground(new java.awt.Color(0, 204, 255));

        chtodos.setText("SELECCIONAR TODOS");
        chtodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chtodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFiltroLayout = new javax.swing.GroupLayout(pnFiltro);
        pnFiltro.setLayout(pnFiltroLayout);
        pnFiltroLayout.setHorizontalGroup(
            pnFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiltroLayout.createSequentialGroup()
                .addComponent(chtodos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnFiltroLayout.setVerticalGroup(
            pnFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiltroLayout.createSequentialGroup()
                .addComponent(chtodos)
                .addGap(0, 413, Short.MAX_VALUE))
        );

        btEnviar.setBackground(new java.awt.Color(0, 204, 255));
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btEnviar)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        // TODO add your handling code here:
        for(JCheckBox i: checks){
            if (i.isSelected()){
                this.titulos.add(i.getText());
            }
        }
        this.setVisible(false);
        fmain.setEnabled(true);
        fmain.setVisibletcontenido(true);
        fmain.cargarTabla(this.titulos, titles);   
        
    }//GEN-LAST:event_btEnviarActionPerformed

    private void chtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chtodosActionPerformed
        if (this.chtodos.isSelected()){
            for(JCheckBox i: checks){
                i.setSelected(true);
            }
        }else{
            for(JCheckBox i: checks){
                i.setSelected(false);
            }
        } 
        
    }//GEN-LAST:event_chtodosActionPerformed
    public LinkedList getTitulosSeleccionados(){
        return this.titulos;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new frFiltro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JCheckBox chtodos;
    private javax.swing.JPanel pnFiltro;
    // End of variables declaration//GEN-END:variables
}
